# Generated by Django 3.2.9 on 2021-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_or_company_name', models.CharField(blank=True, max_length=80, null=True)),
                ('citizen', models.BooleanField(default=True)),
                ('company', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.IntegerField()),
                ('PIB_JMBG', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
