# Generated by Django 3.2.9 on 2021-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupac',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
